# Dockerfile.web

# --- Build stage ---
FROM node:20-alpine as build
WORKDIR /app
COPY frontend/tars-frontend/package*.json ./
RUN npm ci
COPY frontend/tars-frontend ./
RUN npm run build

# --- Serve stage ---
FROM nginx:1.27-alpine
# Nginx config
COPY deploy/nginx.conf /etc/nginx/conf.d/default.conf
# Static app
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
